const $ = (x) => document.getElementById(x);
let img = null,
	file = null,
	code = '',
	name = 'image_rgb565';
const boards = { devkit: [5, 2, 4], s3: [5, 6, 7], c3: [7, 6, 10], 8266: [15, 4, 16], custom: [5, 2, 4] },
	sizes = {
		1.3: [240, 240, ['ST7789']],
		1.8: [128, 160, ['ST7735']],
		2.4: [240, 320, ['ILI9341']],
		2.8: [240, 320, ['ILI9341', 'ST7789']],
	};
function toast(t) {
	$('toast').textContent = t;
	$('toast').classList.add('show');
	clearTimeout(toast.t);
	toast.t = setTimeout(() => $('toast').classList.remove('show'), 2100);
}
function mem() {
	let p = (+$('w').value || 1) * (+$('h').value || 1),
		b = p * 2;
	$('mem').textContent =
		b >= 1048576 ? (b / 1048576).toFixed(3) + ' MB' : b >= 1024 ? (b / 1024).toFixed(2) + ' KB' : b + ' B';
	$('detail').textContent = `${p.toLocaleString()} pixels × 2 bytes`;
	$('memtag').textContent = `${p.toLocaleString()} pixels`;
}
function pins() {
	let d = boards[$('board').value];
	$('cs').value = d[0];
	$('dc').value = d[1];
	$('rst').value = d[2];
}
function preset() {
	let d = sizes[$('size').value];
	$('w').value = d[0];
	$('h').value = d[1];
	[...$('driver').options].forEach((o) => (o.hidden = !d[2].includes(o.value)));
	if (!d[2].includes($('driver').value)) $('driver').value = d[2][0];
	mem();
	draw();
}
function load(f) {
	if (!f?.type.startsWith('image/')) return toast('Choose an image file.');
	file = f;
	let u = URL.createObjectURL(f),
		i = new Image();
	i.onload = () => {
		img = i;
		$('thumb').src = u;
		$('fname').textContent = f.name;
		$('fdim').textContent = `${i.naturalWidth} × ${i.naturalHeight}px`;
		$('info').classList.remove('hidden');
		$('convert').disabled = false;
		draw();
		toast('Image loaded.');
	};
	i.src = u;
}
function clear() {
	img = null;
	file = null;
	$('file').value = '';
	$('info').classList.add('hidden');
	$('convert').disabled = true;
	$('canvas').hidden = true;
	$('empty').classList.remove('hidden');
	$('code').value = '';
	code = '';
	$('copy').disabled = $('dh').disabled = $('dm').disabled = $('project').disabled = true;
}
function source(c, w, h) {
	let x = c.getContext('2d', { willReadFrequently: true });
	x.imageSmoothingEnabled = false;
	x.fillStyle = '#000';
	x.fillRect(0, 0, w, h);
	let sw = img.naturalWidth,
		sh = img.naturalHeight,
		m = $('resize').value;
	if (m === 'stretch') x.drawImage(img, 0, 0, w, h);
	else if (m === 'crop') {
		let a = sw / sh,
			b = w / h;
		if (a > b) {
			let nw = sh * b;
			x.drawImage(img, (sw - nw) / 2, 0, nw, sh, 0, 0, w, h);
		} else {
			let nh = sw / b;
			x.drawImage(img, 0, (sh - nh) / 2, sw, nh, 0, 0, w, h);
		}
	} else {
		let s = Math.min(w / sw, h / sh),
			dw = sw * s,
			dh = sh * s;
		x.drawImage(img, (w - dw) / 2, (h - dh) / 2, dw, dh);
	}
	let r = +$('rot').value;
	if (r) {
		let t = document.createElement('canvas');
		t.width = w;
		t.height = h;
		t.getContext('2d').drawImage(c, 0, 0);
		x.clearRect(0, 0, w, h);
		x.save();
		x.translate(w / 2, h / 2);
		x.rotate((r * Math.PI) / 2);
		x.drawImage(t, -w / 2, -h / 2, w, h);
		x.restore();
	}
	return x;
}
function draw() {
	if (!img) return;
	let c = $('canvas'),
		w = +$('w').value,
		h = +$('h').value;
	c.width = w;
	c.height = h;
	source(c, w, h);
	c.hidden = false;
	$('empty').classList.add('hidden');
	$('pmeta').textContent = `${w} × ${h}px · ${$('driver').value} · RGB565`;
}
function id(n) {
	let s = (n || 'image').replace(/\.[^/.]+$/, '').replace(/[^a-zA-Z0-9_]/g, '_');
	if (!s) s = 'image';
	if (/^\d/.test(s)) s = '_' + s;
	return s.toLowerCase() + '_rgb565';
}
function gen() {
	if (!img) return;
	let w = +$('w').value,
		h = +$('h').value,
		c = document.createElement('canvas');
	c.width = w;
	c.height = h;
	let d = source(c, w, h).getImageData(0, 0, w, h).data,
		v = [];
	for (let i = 0; i < d.length; i += 4) {
		let n = ((d[i] & 248) << 8) | ((d[i + 1] & 252) << 3) | (d[i + 2] >> 3);
		if ($('swap').checked) n = ((n & 255) << 8) | (n >> 8);
		v.push('0x' + n.toString(16).toUpperCase().padStart(4, '0'));
	}
	name = id(file.name);
	let a = [
		'// Generated by ESP32 Image → C Array Converter v1.1.0',
		`// ${w} × ${h}px · RGB565 · ${v.length * 2} bytes`,
		`// Driver: ${$('driver').value}`,
		'',
	];
	if ($('pgm').checked) a.push('#include <pgmspace.h>', '');
	a.push(`const uint16_t ${name}${$('pgm').checked ? ' PROGMEM' : ''}[] = {`);
	for (let i = 0; i < v.length; i += 12)
		a.push('  ' + v.slice(i, i + 12).join(', ') + (i + 12 < v.length ? ',' : ''));
	a.push('};', `// Draw: tft.drawRGBBitmap(0, 0, ${name}, ${w}, ${h});`);
	code = a.join('\n');
	$('code').value = code;
	$('ometa').textContent = `${v.length.toLocaleString()} pixels · ${((v.length * 2) / 1024).toFixed(2)} KB`;
	$('copy').disabled = $('dh').disabled = $('dm').disabled = $('project').disabled = false;
	toast('C array generated.');
}
function main() {
	let lib = $('driver').value,
		w = +$('w').value,
		h = +$('h').value,
		inc = lib === 'ILI9341' ? 'Adafruit_ILI9341.h' : lib === 'ST7735' ? 'Adafruit_ST7735.h' : 'Adafruit_ST7789.h',
		ctor =
			lib === 'ILI9341'
				? `Adafruit_ILI9341 tft(${$('cs').value}, ${$('dc').value}, ${$('rst').value});`
				: lib === 'ST7735'
					? `Adafruit_ST7735 tft(${$('cs').value}, ${$('dc').value}, ${$('rst').value});`
					: `Adafruit_ST7789 tft(${$('cs').value}, ${$('dc').value}, ${$('rst').value});`;
	return `/* Main.ino — generated v1.1.0\n   Display: ${$('size').value}" ${lib} ${w}x${h}\n   GPIO: CS=${$('cs').value}, DC=${$('dc').value}, RST=${$('rst').value}\n   Install Adafruit GFX and ${inc.replace('.h', '')} libraries.\n   Keep image_rgb565.h beside Main.ino. */\n#include <SPI.h>\n#include <Adafruit_GFX.h>\n#include <${inc}>\n#include "image_rgb565.h"\n${ctor}\nvoid setup(){\n  tft.begin();\n  tft.setRotation(${$('rot').value});\n  tft.fillScreen(0x0000);\n  tft.drawRGBBitmap(0,0,${name},${w},${h});\n}\nvoid loop(){}\n`;
}
function dl(n, t, type = 'text/plain') {
	let u = URL.createObjectURL(new Blob([t], { type })),
		a = document.createElement('a');
	a.href = u;
	a.download = n;
	a.click();
	URL.revokeObjectURL(u);
}
function crc(a) {
	let c = -1;
	for (let b of a) {
		c ^= b;
		for (let i = 0; i < 8; i++) c = (c >>> 1) ^ (c & 1 ? 0xedb88320 : 0);
	}
	return (c ^= -1) >>> 0;
}
function zip(items) {
	let e = new TextEncoder(),
		ls = [],
		cs = [],
		off = 0;
	for (let it of items) {
		let n = e.encode(it.name),
			d = e.encode(it.data),
			cr = crc(d),
			l = new Uint8Array(30 + n.length + d.length),
			v = new DataView(l.buffer);
		v.setUint32(0, 0x04034b50, true);
		v.setUint16(4, 20, true);
		v.setUint32(14, cr, true);
		v.setUint32(18, d.length, true);
		v.setUint32(22, d.length, true);
		v.setUint16(26, n.length, true);
		l.set(n, 30);
		l.set(d, 30 + n.length);
		ls.push(l);
		let z = new Uint8Array(46 + n.length),
			q = new DataView(z.buffer);
		q.setUint32(0, 0x02014b50, true);
		q.setUint16(4, 20, true);
		q.setUint16(6, 20, true);
		q.setUint32(16, cr, true);
		q.setUint32(20, d.length, true);
		q.setUint32(24, d.length, true);
		q.setUint16(28, n.length, true);
		q.setUint32(42, off, true);
		z.set(n, 46);
		cs.push(z);
		off += l.length;
	}
	let size = cs.reduce((a, b) => a + b.length, 0),
		end = new Uint8Array(22),
		v = new DataView(end.buffer);
	v.setUint32(0, 0x06054b50, true);
	v.setUint16(8, items.length, true);
	v.setUint16(10, items.length, true);
	v.setUint32(12, size, true);
	v.setUint32(16, off, true);
	return new Blob([...ls, ...cs, end], { type: 'application/zip' });
}
function project() {
	let b = zip([
			{ name: 'ESP32_TFT_Project/Main.ino', data: main() },
			{ name: 'ESP32_TFT_Project/image_rgb565.h', data: code },
		]),
		u = URL.createObjectURL(b),
		a = document.createElement('a');
	a.href = u;
	a.download = 'ESP32_TFT_Project.zip';
	a.click();
	URL.revokeObjectURL(u);
	toast('Project ZIP downloaded.');
}
$('file').onchange = (e) => load(e.target.files[0]);
$('remove').onclick = clear;
$('board').onchange = pins;
$('size').onchange = preset;
[$('w'), $('h'), $('driver'), $('resize'), $('rot'), $('swap'), $('pgm'), $('cs'), $('dc'), $('rst')].forEach((e) => {
	e.oninput = () => {
		mem();
		draw();
	};
	e.onchange = () => {
		mem();
		draw();
	};
});
$('convert').onclick = gen;
$('copy').onclick = async () => {
	try {
		await navigator.clipboard.writeText(code);
		toast('C code copied.');
	} catch {
		$('code').select();
		document.execCommand('copy');
	}
};
$('dh').onclick = () => dl('image_rgb565.h', code, 'text/x-c');
$('dm').onclick = () => dl('Main.ino', main());
$('project').onclick = project;
$('reset').onclick = () => {
	board.value = 'devkit';
	size.value = '2.4';
	driver.value = 'ILI9341';
	resize.value = 'fit';
	rot.value = '0';
	swap.checked = false;
	pgm.checked = true;
	pins();
	preset();
	toast('Settings reset');
};
['dragenter', 'dragover'].forEach((t) => (drop.ondrop = (e) => load(e.dataTransfer.files[0])));
drop.ondragover = (e) => e.preventDefault();
drop.ondragenter = (e) => e.preventDefault();
pins();
preset();
mem();
